name: Bundler audit
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout repository
    - uses: ruby/setup-ruby@v1
      name: Setup ruby
      with:
        ruby-version: 3.2
        bundler-cache: true
    - run: bundle exec bundle-audit
      name: Run bundle audit
