name: HAML-Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run HAML-Lint
      run: bundle exec haml-lint
