name: RSpec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1']
        rails-version: ['rails6', 'rails7']
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.rails-version }}.gemfile
    steps:
    - uses: actions/checkout@v3
      name: Checkout repository
    - uses: ruby/setup-ruby@v1
      name: Setup ruby
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - run: bundle exec appraisal ${{ matrix.rails-version }} rspec
      name: Run specs
    - uses: paambaati/codeclimate-action@v3.0.0
      name: Publish code coverage
